# Generated by Django 5.1.3 on 2024-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('custom_add_document', 'Can custom add document'), ('custom_view_document', 'Can custom view document')],
            },
        ),
    ]
