# Generated by Django 5.1.3 on 2024-12-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_content_remove_document_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagetransition',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
        ),
    ]
