# Generated by Django 5.1.3 on 2024-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_stagetransition_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='waiting for IA'),
        ),
    ]
