# Generated by Django 5.1.3 on 2024-12-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='workflow_instance',
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instance', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_instances', to='documents.workflowstage'),
        ),
    ]
