# Generated by Django 5.1.3 on 2024-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_stagetransition_from_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nextcloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='synced_to_nextcloud',
            field=models.BooleanField(default=False),
        ),
    ]
